name:                advent2020
version:             0.1.0.0
github:              "egnwd/advent2020"
license:             BSD3
author:              "Elliot Greenwood"
maintainer:          "hello@elliotgreenwood.co.uk"
copyright:           "2020 Elliot Greenwood"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/egnwd/advent2020#readme>

dependencies:
- base >= 4.7 && < 5
- doctest   ^>= 0.17
- directory ^>= 1.3
- filepath  ^>= 1.4
- megaparsec ^>= 9.0
- text
- containers
- mtl
- vector
- pointedlist
- lens
- barbies
- refined
- finite-typelits
- one-liner-instances

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - DataKinds
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - LambdaCase
  - MultiWayIf
  - RecordWildCards
  - TupleSections
  - TypeOperators
  - OverloadedStrings
  - ScopedTypeVariables
  - GADTs
  - NumericUnderscores
  - DeriveFunctor
  - DeriveFoldable

_default-exe: &day-exe
  source-dirs:  execs
  dependencies:
  - advent2020
  other-modules: []

library:
  source-dirs: src

executables:
  day1:
    <<:   *day-exe
    main: Day01.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day01
  day2:
    <<:   *day-exe
    main: Day02.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day02
  day3:
    <<:   *day-exe
    main: Day03.hs
    ghc-options: !flatten
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day03
  day4:
    <<:   *day-exe
    main: Day04.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day04
  day5:
    <<:   *day-exe
    main: Day05.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day05
  day6:
    <<:   *day-exe
    main: Day06.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day06
  day7:
    <<:   *day-exe
    main: Day07.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Day07

tests:
  advent2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         *exe-ghc-options
    dependencies:
    - advent2020
    - doctest
    - directory
    - filepath
