name:                advent2020
version:             0.1.0.0
github:              "egnwd/advent2020"
license:             BSD3
author:              "Elliot Greenwood"
maintainer:          "hello@elliotgreenwood.co.uk"
copyright:           "2020 Elliot Greenwood"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            fun

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/egnwd/advent2020#readme>

dependencies:
- base >= 4.7 && < 5
- doctest   ^>= 0.17
- directory ^>= 1.3
- filepath  ^>= 1.4

library:
  source-dirs: src

executables:
  day1:
    main:                Day01.hs
    source-dirs:         execs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2020

tests:
  advent2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2020
    - doctest
    - directory
    - filepath
