name:                advent2020
version:             0.1.0.0
github:              "egnwd/advent2020"
license:             BSD3
author:              "Elliot Greenwood"
maintainer:          "hello@elliotgreenwood.co.uk"
copyright:           "2020 Elliot Greenwood"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/egnwd/advent2020#readme>

dependencies:
- base >= 4.7 && < 5
- doctest   ^>= 0.17
- directory ^>= 1.3
- filepath  ^>= 1.4
- megaparsec ^>= 9.0
- text

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

_default-exe: &day-exe
  source-dirs:  execs
  ghc-options:  *exe-ghc-options
  dependencies:
  - advent2020
  other-modules: []

library:
  source-dirs: src

executables:
  day1:
    <<:   *day-exe
    main: Day01.hs
  day2:
    <<:   *day-exe
    main: Day02.hs

tests:
  advent2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         *exe-ghc-options
    dependencies:
    - advent2020
    - doctest
    - directory
    - filepath
